name: Test

permissions:
  id-token: write
  contents: read

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: npm
      - run: npm ci --include=dev
      - run: npm run test